// Code generated by protoc-gen-go. DO NOT EDIT.
// source: netvuln.proto

package netvuln_v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CheckVulnRequest struct {
	Targets              []string `protobuf:"bytes,1,rep,name=targets,proto3" json:"targets,omitempty"`
	TcpPort              []int32  `protobuf:"varint,2,rep,packed,name=tcp_port,json=tcpPort,proto3" json:"tcp_port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckVulnRequest) Reset()         { *m = CheckVulnRequest{} }
func (m *CheckVulnRequest) String() string { return proto.CompactTextString(m) }
func (*CheckVulnRequest) ProtoMessage()    {}
func (*CheckVulnRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_54e30c2988138cb9, []int{0}
}

func (m *CheckVulnRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckVulnRequest.Unmarshal(m, b)
}
func (m *CheckVulnRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckVulnRequest.Marshal(b, m, deterministic)
}
func (m *CheckVulnRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckVulnRequest.Merge(m, src)
}
func (m *CheckVulnRequest) XXX_Size() int {
	return xxx_messageInfo_CheckVulnRequest.Size(m)
}
func (m *CheckVulnRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckVulnRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CheckVulnRequest proto.InternalMessageInfo

func (m *CheckVulnRequest) GetTargets() []string {
	if m != nil {
		return m.Targets
	}
	return nil
}

func (m *CheckVulnRequest) GetTcpPort() []int32 {
	if m != nil {
		return m.TcpPort
	}
	return nil
}

type CheckVulnResponse struct {
	Results              []*TargetResult `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *CheckVulnResponse) Reset()         { *m = CheckVulnResponse{} }
func (m *CheckVulnResponse) String() string { return proto.CompactTextString(m) }
func (*CheckVulnResponse) ProtoMessage()    {}
func (*CheckVulnResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_54e30c2988138cb9, []int{1}
}

func (m *CheckVulnResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckVulnResponse.Unmarshal(m, b)
}
func (m *CheckVulnResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckVulnResponse.Marshal(b, m, deterministic)
}
func (m *CheckVulnResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckVulnResponse.Merge(m, src)
}
func (m *CheckVulnResponse) XXX_Size() int {
	return xxx_messageInfo_CheckVulnResponse.Size(m)
}
func (m *CheckVulnResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckVulnResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CheckVulnResponse proto.InternalMessageInfo

func (m *CheckVulnResponse) GetResults() []*TargetResult {
	if m != nil {
		return m.Results
	}
	return nil
}

type TargetResult struct {
	Target               string     `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	Services             []*Service `protobuf:"bytes,2,rep,name=services,proto3" json:"services,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *TargetResult) Reset()         { *m = TargetResult{} }
func (m *TargetResult) String() string { return proto.CompactTextString(m) }
func (*TargetResult) ProtoMessage()    {}
func (*TargetResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_54e30c2988138cb9, []int{2}
}

func (m *TargetResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TargetResult.Unmarshal(m, b)
}
func (m *TargetResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TargetResult.Marshal(b, m, deterministic)
}
func (m *TargetResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TargetResult.Merge(m, src)
}
func (m *TargetResult) XXX_Size() int {
	return xxx_messageInfo_TargetResult.Size(m)
}
func (m *TargetResult) XXX_DiscardUnknown() {
	xxx_messageInfo_TargetResult.DiscardUnknown(m)
}

var xxx_messageInfo_TargetResult proto.InternalMessageInfo

func (m *TargetResult) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

func (m *TargetResult) GetServices() []*Service {
	if m != nil {
		return m.Services
	}
	return nil
}

type Service struct {
	Name                 string           `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version              string           `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	TcpPort              int32            `protobuf:"varint,3,opt,name=tcp_port,json=tcpPort,proto3" json:"tcp_port,omitempty"`
	Vulns                []*Vulnerability `protobuf:"bytes,4,rep,name=vulns,proto3" json:"vulns,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Service) Reset()         { *m = Service{} }
func (m *Service) String() string { return proto.CompactTextString(m) }
func (*Service) ProtoMessage()    {}
func (*Service) Descriptor() ([]byte, []int) {
	return fileDescriptor_54e30c2988138cb9, []int{3}
}

func (m *Service) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Service.Unmarshal(m, b)
}
func (m *Service) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Service.Marshal(b, m, deterministic)
}
func (m *Service) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Service.Merge(m, src)
}
func (m *Service) XXX_Size() int {
	return xxx_messageInfo_Service.Size(m)
}
func (m *Service) XXX_DiscardUnknown() {
	xxx_messageInfo_Service.DiscardUnknown(m)
}

var xxx_messageInfo_Service proto.InternalMessageInfo

func (m *Service) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Service) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *Service) GetTcpPort() int32 {
	if m != nil {
		return m.TcpPort
	}
	return 0
}

func (m *Service) GetVulns() []*Vulnerability {
	if m != nil {
		return m.Vulns
	}
	return nil
}

type Vulnerability struct {
	Identifier           string   `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	CvssScore            float32  `protobuf:"fixed32,2,opt,name=cvss_score,json=cvssScore,proto3" json:"cvss_score,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Vulnerability) Reset()         { *m = Vulnerability{} }
func (m *Vulnerability) String() string { return proto.CompactTextString(m) }
func (*Vulnerability) ProtoMessage()    {}
func (*Vulnerability) Descriptor() ([]byte, []int) {
	return fileDescriptor_54e30c2988138cb9, []int{4}
}

func (m *Vulnerability) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Vulnerability.Unmarshal(m, b)
}
func (m *Vulnerability) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Vulnerability.Marshal(b, m, deterministic)
}
func (m *Vulnerability) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Vulnerability.Merge(m, src)
}
func (m *Vulnerability) XXX_Size() int {
	return xxx_messageInfo_Vulnerability.Size(m)
}
func (m *Vulnerability) XXX_DiscardUnknown() {
	xxx_messageInfo_Vulnerability.DiscardUnknown(m)
}

var xxx_messageInfo_Vulnerability proto.InternalMessageInfo

func (m *Vulnerability) GetIdentifier() string {
	if m != nil {
		return m.Identifier
	}
	return ""
}

func (m *Vulnerability) GetCvssScore() float32 {
	if m != nil {
		return m.CvssScore
	}
	return 0
}

func init() {
	proto.RegisterType((*CheckVulnRequest)(nil), "netvuln.v1.CheckVulnRequest")
	proto.RegisterType((*CheckVulnResponse)(nil), "netvuln.v1.CheckVulnResponse")
	proto.RegisterType((*TargetResult)(nil), "netvuln.v1.TargetResult")
	proto.RegisterType((*Service)(nil), "netvuln.v1.Service")
	proto.RegisterType((*Vulnerability)(nil), "netvuln.v1.Vulnerability")
}

func init() {
	proto.RegisterFile("netvuln.proto", fileDescriptor_54e30c2988138cb9)
}

var fileDescriptor_54e30c2988138cb9 = []byte{
	// 328 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x52, 0x4d, 0x4b, 0xc3, 0x40,
	0x14, 0x34, 0xfd, 0x4a, 0xf3, 0x6a, 0x45, 0x57, 0x90, 0xad, 0x58, 0x09, 0x39, 0xf5, 0xd4, 0x62,
	0xfc, 0x09, 0x1e, 0x0a, 0x1e, 0x8a, 0x6c, 0x45, 0x2f, 0x42, 0x49, 0xe3, 0x53, 0x17, 0xe3, 0x6e,
	0xdc, 0xdd, 0x04, 0x3c, 0xfb, 0xc7, 0x25, 0x9b, 0xa4, 0x6e, 0x05, 0x6f, 0x99, 0x79, 0xc3, 0xbc,
	0x99, 0xbc, 0x85, 0xb1, 0x40, 0x53, 0x16, 0x99, 0x98, 0xe7, 0x4a, 0x1a, 0x49, 0xa0, 0x85, 0xe5,
	0x55, 0xb4, 0x84, 0xe3, 0x9b, 0x37, 0x4c, 0xdf, 0x1f, 0x8a, 0x4c, 0x30, 0xfc, 0x2c, 0x50, 0x1b,
	0x42, 0xc1, 0x37, 0x89, 0x7a, 0x45, 0xa3, 0xa9, 0x17, 0x76, 0x67, 0x01, 0x6b, 0x21, 0x99, 0xc0,
	0xd0, 0xa4, 0xf9, 0x26, 0x97, 0xca, 0xd0, 0x4e, 0xd8, 0x9d, 0xf5, 0x99, 0x6f, 0xd2, 0xfc, 0x4e,
	0x2a, 0x13, 0x2d, 0xe1, 0xc4, 0x31, 0xd2, 0xb9, 0x14, 0x1a, 0x49, 0x0c, 0xbe, 0x42, 0x5d, 0x64,
	0x8d, 0xd3, 0x28, 0xa6, 0xf3, 0xdf, 0xdd, 0xf3, 0x7b, 0xeb, 0xca, 0xac, 0x80, 0xb5, 0xc2, 0xe8,
	0x11, 0x0e, 0xdd, 0x01, 0x39, 0x83, 0x41, 0xbd, 0x9e, 0x7a, 0xa1, 0x37, 0x0b, 0x58, 0x83, 0xc8,
	0x02, 0x86, 0x1a, 0x55, 0xc9, 0x53, 0xd4, 0x36, 0xcb, 0x28, 0x3e, 0x75, 0xcd, 0xd7, 0xf5, 0x8c,
	0xed, 0x44, 0xd1, 0xb7, 0x07, 0x7e, 0xc3, 0x12, 0x02, 0x3d, 0x91, 0x7c, 0x60, 0x63, 0x69, 0xbf,
	0xab, 0xda, 0x25, 0x2a, 0xcd, 0xa5, 0xa0, 0x1d, 0x4b, 0xb7, 0x70, 0xaf, 0x76, 0x37, 0xf4, 0x9c,
	0xda, 0x64, 0x01, 0xfd, 0x6a, 0xa3, 0xa6, 0x3d, 0x1b, 0x61, 0xe2, 0x46, 0xa8, 0x7e, 0x05, 0xaa,
	0x64, 0xcb, 0x33, 0x6e, 0xbe, 0x58, 0xad, 0x8b, 0x56, 0x30, 0xde, 0xe3, 0xc9, 0x25, 0x00, 0x7f,
	0x46, 0x61, 0xf8, 0x0b, 0x47, 0xd5, 0x04, 0x72, 0x18, 0x32, 0x05, 0x48, 0x4b, 0xad, 0x37, 0x3a,
	0x95, 0x0a, 0x6d, 0xb2, 0x0e, 0x0b, 0x2a, 0x66, 0x5d, 0x11, 0xf1, 0x13, 0x1c, 0xad, 0xd0, 0x54,
	0x96, 0x6d, 0xb7, 0x5b, 0x08, 0x76, 0x97, 0x20, 0x17, 0x6e, 0xa0, 0xbf, 0x97, 0x3e, 0x9f, 0xfe,
	0x33, 0xad, 0xcf, 0x17, 0x1d, 0x6c, 0x07, 0xf6, 0xc5, 0x5c, 0xff, 0x04, 0x00, 0x00, 0xff, 0xff,
	0x07, 0xa2, 0x23, 0x07, 0x42, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// NetVulnServiceClient is the client API for NetVulnService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type NetVulnServiceClient interface {
	CheckVuln(ctx context.Context, in *CheckVulnRequest, opts ...grpc.CallOption) (*CheckVulnResponse, error)
}

type netVulnServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNetVulnServiceClient(cc grpc.ClientConnInterface) NetVulnServiceClient {
	return &netVulnServiceClient{cc}
}

func (c *netVulnServiceClient) CheckVuln(ctx context.Context, in *CheckVulnRequest, opts ...grpc.CallOption) (*CheckVulnResponse, error) {
	out := new(CheckVulnResponse)
	err := c.cc.Invoke(ctx, "/netvuln.v1.NetVulnService/CheckVuln", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NetVulnServiceServer is the server API for NetVulnService service.
type NetVulnServiceServer interface {
	CheckVuln(context.Context, *CheckVulnRequest) (*CheckVulnResponse, error)
}

// UnimplementedNetVulnServiceServer can be embedded to have forward compatible implementations.
type UnimplementedNetVulnServiceServer struct {
}

func (*UnimplementedNetVulnServiceServer) CheckVuln(ctx context.Context, req *CheckVulnRequest) (*CheckVulnResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckVuln not implemented")
}

func RegisterNetVulnServiceServer(s *grpc.Server, srv NetVulnServiceServer) {
	s.RegisterService(&_NetVulnService_serviceDesc, srv)
}

func _NetVulnService_CheckVuln_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckVulnRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetVulnServiceServer).CheckVuln(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/netvuln.v1.NetVulnService/CheckVuln",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetVulnServiceServer).CheckVuln(ctx, req.(*CheckVulnRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _NetVulnService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "netvuln.v1.NetVulnService",
	HandlerType: (*NetVulnServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckVuln",
			Handler:    _NetVulnService_CheckVuln_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "netvuln.proto",
}
